### ISSUE TITLE
Incorrect Difficulty for rated levels with differing star count

### ISSUE THREAD

**Issue by Aktimoose** [TechStudent10/DiscordRPC#1] opened 2023-12-02 20:58 UTC
For any rated level, the mod will determine the difficulty to show in the RPC with the star count. This causes an issue with a few levels, namely the main levels (with every level that's 10 stars or greater just being NA) (it also just leaves the creator section blank)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/b213a767-374d-4b9e-94aa-dea6b01657a2)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/8b0196d1-b895-42c6-88f7-f19b58d66087)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/947b71fe-8363-4804-ac97-b3b31462b920)

As well as Luster by eopc (which is easy rated)
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/4e28f054-7683-43e3-bb72-a76b51a479f2)

This no star auto level also has an incorrect difficulty idk why
![image](https://github.com/TechStudent10/DiscordRPC/assets/44620677/6f38faa0-3b05-45c8-9657-22d521982298)

**Comment by TechStudent10** [comment] 2023-12-02 21:19
The RobTop levels I'm planning on fixing (already reported to me in a Discord server) + they are the only (non-hacked) rated levels in the game with a star count <10 so I can probably hard code it if I really have to.

As for Luster I'm probably going to leave it because it's an issue on Rob's end, as well as it being such a rare edge case.

The no-star auto thing is probably due to the fact that I use the enum that GD uses to determine icon faces in the event that a level is unrated (stars = 0). It must be set to display the hard face for some reason. Again, an edge case.

**Comment by TechStudent10** [comment] 2023-12-02 22:06
@Aktimoose can you send me the ID for the auto no-star level?

**Comment by Aktimoose** [comment] 2023-12-03 00:16
> @Aktimoose can you send me the ID for the auto no-star level?

503047

**Comment by TechStudent10** [comment] 2023-12-08 21:46
I'm not sure what the issue is for the auto no star level tbh. It's difficulty face is set to the hard face even though in game it shows up as auto.
I'd most likely have to hard-code this in, which for such a rare level really doesn't matter.
Main levels were fixed in commits https://github.com/TechStudent10/DiscordRPC/commit/bd498696dbf7bdec9eb5f3cddf0fa7979dc1b2de and https://github.com/TechStudent10/DiscordRPC/commit/a2adf547f2fe579a17847d00295421d5763a9165, so I'm gonna go ahead and close this issue.

**Closed as completed by TechStudent10** 2023-12-08 21:46 UTC
Labels: bug
